# Generated by Django 3.2.4 on 2021-08-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('recipient', models.EmailField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('hasRead', models.BooleanField(default=False)),
            ],
        ),
    ]
